variables:
  GIT_SUBMODULE_STRATEGY: recursive

.before_ubuntu: &before_ubuntu
  - export DEBIAN_FRONTEND="noninteractive"
  - >
    apt-get update -qq &&      \
      apt-get install -y -qq   \
        binutils-arm-none-eabi \
        build-essential        \
        cmake                  \
        git                    \
        graphviz               \
        libgraphviz-dev        \
        liblpsolve55-dev       \
        liblzma-dev            \
        libssh2-1              \
        libssh2-1-dev          \
        libssl-dev             \
        llvm                   \
        locales                \
        lp-solve               \
        patch                  \
        pkg-config             \
        rake                   \
        ruby                   \
        ruby-bundler           \
        ruby-dev               \
        zlib1g-dev
  - sed -i -e 's/# C.UTF-8 UTF-8/C.UTF-8 UTF-8/' /etc/locale.gen
  - dpkg-reconfigure --frontend=noninteractive locales
  - update-locale LANG=C.UTF-8
  - export LD_LIBRARY_PATH="/usr/lib/lp_solve:$LD_LIBRARY_PATH"
  - export LANG=C.UTF-8

.before_gems: &before_gems
  - export GEM_HOME="$(pwd)/gems"
  - gem install rake
  - bundle install
  - export PATH="$(pwd):$PATH"

.tests:
  stage:  test
  script: bundle exec ruby ./test/testrunner.rb -v -v

test:ubuntu:latest:
  extends: .tests
  image: ubuntu:latest
  before_script:
    - *before_ubuntu
    - *before_gems

test:ubuntu:rolling:
  extends: .tests
  image: ubuntu:rolling
  before_script:
    - *before_ubuntu
    - *before_gems

test:archlinux:rolling:
  extends: .tests
  image: archlinux:latest
  before_script:
    - >
      pacman -Syy &&               \
        pacman -Syu --noconfirm && \
        pacman -S --noconfirm      \
          arm-none-eabi-binutils   \
          base-devel               \
          cmake                    \
          git                      \
          graphviz                 \
          libpng                   \
          librsvg                  \
          llvm                     \
          lpsolve                  \
          ruby                     \
          ruby-bundler             \
          ruby-rake                \
          rubygems
    # Some docker configurations break chroot and thus graphviz-pluginconfig
    # in graphviz .postinstall script, therefore rerun it
    - /usr/bin/dot -c
    - *before_gems
